name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            client/node_modules
            ~/.npm
          key: frontend-npm-${{ matrix.node-version }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            frontend-npm-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Lint
        run: npm run lint
        working-directory: ./client

      - name: Typecheck
        run: npm run typecheck
        working-directory: ./client

      - name: Run tests (CI)
        env:
          CI: true
        run: |
          npm run test:ci -- --reporters=default --reporters=jest-junit
        working-directory: ./client

      - name: Upload test report (junit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-report
          path: client/junit.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: client/coverage

      - name: Build
        run: npm run build
        working-directory: ./client
